#pragma once
#include "objects/transform.h"
#include "objects/object.h"
#include "objects/models.h"
#include "objects/verticesObject.h"
#include "objects/coloredVerticesObject.h"
#include "objects/indexedColoredVerticesObject.h"
#include "objects/modelObject.h"
#include "objects/component.h"